"""
Sliding-window change-point detector using KL divergence.

Plain English: Imagine comparing two neighbouring windows of data — one looking
back ("past") and one looking forward ("recent").  If the device is stable, both
windows should look similar.  The moment the noise level shifts, the two windows
will start to differ.  We quantify "how different" with KL divergence, a measure
from information theory that asks: "how surprised would I be if data from the
past window were actually generated by the distribution I fitted to the recent
window?"

For binary quantum measurement data, each window gives an estimate of the
bit-flip probability p (past) and q (recent).  The symmetric KL divergence
between two Bernoulli(p) and Bernoulli(q) distributions has a clean formula:

    KL_sym(p, q) = KL(p||q) + KL(q||p)
                 = p*log(p/q) + (1-p)*log((1-p)/(1-q))
                 + q*log(q/p) + (1-q)*log((1-q)/(1-p))

When KL_sym exceeds a threshold, we declare a changepoint.
"""

import numpy as np
from typing import Optional


def _kl_bernoulli(p: float, q: float, eps: float = 1e-10) -> float:
    """
    KL divergence from Bernoulli(p) to Bernoulli(q): KL(p || q).

    This measures how much information is lost when you approximate
    the true distribution p with the approximation q.

    Args:
        p   : true probability (e.g. past bit-flip rate).
        q   : approximate probability (e.g. recent bit-flip rate).
        eps : small constant to avoid log(0).

    Returns:
        KL divergence (non-negative float).
    """
    p = np.clip(p, eps, 1.0 - eps)
    q = np.clip(q, eps, 1.0 - eps)
    return p * np.log(p / q) + (1.0 - p) * np.log((1.0 - p) / (1.0 - q))


def run_window_detector(
    bit_flip_rates: np.ndarray,
    window_size: int = 10,
    threshold: float = 0.05,
) -> dict:
    """
    Run the sliding-window KL-divergence detector on a bit-flip rate time series.

    At each timestep t (once we have enough data), the detector:
        1. Takes the "past" window:   bit_flip_rates[t - window_size : t]
        2. Takes the "recent" window: bit_flip_rates[t : t + window_size]
        3. Estimates the bit-flip probability in each window (just the mean).
        4. Computes the symmetric KL divergence between the two Bernoulli
           distributions.
        5. If KL_sym > threshold, raises an alarm.

    The detection point is reported as the centre of the boundary between the
    two windows (index t), so the reported changepoint is the first t where
    KL_sym crosses the threshold.

    Args:
        bit_flip_rates: 1D array of bit-flip rates, one value per timestep.
        window_size   : Number of timesteps in each window (W).
                        Larger windows give more stable estimates but slower
                        detection. A good default is 10% of total length.
        threshold     : KL divergence threshold. Values near 0.05 catch moderate
                        shifts; values near 0.02 are more sensitive (more false
                        alarms). Tune by looking at the score plot first.

    Returns:
        dict with keys:
            'scores'      : 1D float array of KL_sym values, shape (n_timesteps,).
                            Scores before window_size and after n - window_size
                            are set to 0.0 (insufficient data).
            'detected_at' : int timestep of first detection (centre of boundary),
                            or None if no alarm raised.
            'threshold'   : the threshold used (for plotting convenience).

    Example:
        >>> rates = np.array([0.01] * 50 + [0.05] * 50)
        >>> result = run_window_detector(rates, window_size=10, threshold=0.05)
        >>> print(result['detected_at'])  # Should be close to 50
    """
    n = len(bit_flip_rates)
    scores = np.zeros(n)
    detected_at: Optional[int] = None

    for t in range(window_size, n - window_size):
        past_window = bit_flip_rates[t - window_size : t]
        recent_window = bit_flip_rates[t : t + window_size]

        # Estimate bit-flip probability in each window.
        p_past = float(np.mean(past_window))
        p_recent = float(np.mean(recent_window))

        # Symmetric KL divergence: average of both directions.
        kl_sym = _kl_bernoulli(p_past, p_recent) + _kl_bernoulli(p_recent, p_past)
        scores[t] = kl_sym

        if detected_at is None and kl_sym > threshold:
            detected_at = t

    return {
        "scores": scores,
        "detected_at": detected_at,
        "threshold": threshold,
    }
